# Generated by Django 3.2.9 on 2021-12-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webawards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
